version: '3.4'
services:
  web:
    build: .
    command: python3 manage.py runserver 0:8000
    ports:
      - 8000:8000 
  worker:
    build: .
    image: &img worker 
    command: celery -A wololo.tasks worker -l info --statedb=wololo/celery/worker.state
    depends_on:
      - rabbitmq
    restart: 'no'
  
  rabbitmq:
    image: rabbitmq:3.7.8

  redis:
    image: redis:2.8
    ports:
      - 6379:6379