version: '3.4'
services: 
  worker:
    build: .
    image: &img worker 
    command: [celery, '-A', 'wololo.tasks', worker, -l, info, ---statedb=celery/worker.state]
    # environment: &env      
    #   - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
    #   - MINIO_HOST=minio:9000
    #   - MINIO_ACCESS_KEY=token
    #   - MINIO_SECRET_KEY=secret
    #   - NEWSPAPER_URLS=https://www.theguardian.com,https://www.nytimes.com
    #   - NEWSPAPER_SCHEDULE=300
    depends_on:
      - rabbitmq
    restart: 'no'
    volumes:
      - ./wololo:/wololo 
  
  rabbitmq:
    image: rabbitmq:3.7.8

  redis:
    image: redis:2.8
    ports:
      - 6379:6379