"""
Django settings for DjangoFirebaseProject project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#t3@=2zz%&ujegnkco#yb#e=5pwdme30*8th9kq*@7rzje!vs+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'channels',
    'wololo',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DjangoFirebaseProject.urls'
ASGI_APPLICATION = 'DjangoFirebaseProject.routing.application'
CHANNEL_LAYERS = ***REMOVED***
    'default': ***REMOVED***
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': ***REMOVED***
            "hosts": [('localhost', 6379)],
        ***REMOVED***,
    ***REMOVED***,
***REMOVED***

TEMPLATES = [
    ***REMOVED***
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': ***REMOVED***
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        ***REMOVED***,
    ***REMOVED***,
]



WSGI_APPLICATION = 'DjangoFirebaseProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = ***REMOVED***
    'default': ***REMOVED***
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    ***REMOVED***
***REMOVED***


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    ***REMOVED***
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    ***REMOVED***,
    ***REMOVED***
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    ***REMOVED***,
    ***REMOVED***
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    ***REMOVED***,
    ***REMOVED***
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    ***REMOVED***,
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
LOGIN_REDIRECT_URL = '/game'
LANDING_PAGE_REDIRECT_URL = '/'
